version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    command: ["--config.file=/prometheus-data/prometheus.yml"]
    volumes:
      - ./prometheus-data:/prometheus-data
      - prometheus:/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - ${GRAFANA_PORT}:3003
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  prometheus:
  grafana-storage: