global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    honor_labels: false
    honor_timestamps: true
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
    static_configs:
      - targets: ['${API_HOST}:${PROMETHEUS_PORT}']
  - job_name: class
    static_configs:
    - targets: 
      - ${IP}:3000